---
- name: install filebeat to remote hosts
  hosts: testservers
  become: yes
  remote_user: ansible_user
  gather_facts: yes
  roles:
    - geerlingguy.filebeat
          #- ../roles/geerlingguy.filebeat
